# -*- coding: utf-8 -*-
"""Finel_project_MLL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rsR5G4yS8jbS8EzaOuy2WU4IsNqyx1ol
"""


from sentence_transformers import SentenceTransformer
import pandas as pd

# We will use pandas to read the CSV file. Assuming the dreams are in the first column, we convert it to a list.
dreams_df = pd.read_csv('all_dreams_combined.csv')
dreams = dreams_df.iloc[:, 0].tolist()

len(dreams)

# Load embedding model
model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

# Create embeddings for the toy dreams
embeddings = model.encode(dreams, show_progress_bar=True)

print("Embeddings shape:", embeddings.shape)



print("Shape of the embeddings array:")
print(embeddings.shape)
