# -*- coding: utf-8 -*-
"""Finel_project_MLL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rsR5G4yS8jbS8EzaOuy2WU4IsNqyx1ol
"""

!pip install -q sentence-transformers pandas

from sentence_transformers import SentenceTransformer
import pandas as pd

# Small toy list of dreams
dreams = [
    "I was running through a dark forest and someone was chasing me.",
    "I dreamed that I was flying over a big city and felt very free.",
    "I was late to an important exam and couldn't find the classroom.",
    "I met my grandma in a strange house and we talked for hours.",
    "I was in the ocean and a huge wave was coming toward me."
]

len(dreams)

# Load embedding model
model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

# Create embeddings for the toy dreams
embeddings = model.encode(dreams, show_progress_bar=True)

print("Embeddings shape:", embeddings.shape)

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_excel("all_dreams_combined.xlsx")

df.shape

from sklearn.decomposition import PCA

pca = PCA(n_components=2)
embeddings_2d = pca.fit_transform(embeddings)

embeddings_2d.shape

df.columns

dreams = df["dream"].astype(str).tolist()
len(dreams)

from sentence_transformers import SentenceTransformer

model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

# להתחלה – רק 1000 חלומות
dreams_subset = dreams[:1000]

embeddings = model.encode(dreams_subset, show_progress_bar=True)

print("Embeddings shape:", embeddings.shape)

from sklearn.decomposition import PCA

pca = PCA(n_components=2)
embeddings_2d = pca.fit_transform(embeddings)

print("2D shape:", embeddings_2d.shape)
print("Explained variance:", pca.explained_variance_ratio_,
      "sum =", pca.explained_variance_ratio_.sum())

import matplotlib.pyplot as plt

x = embeddings_2d[:, 0]
y = embeddings_2d[:, 1]

plt.figure(figsize=(8, 6))
plt.scatter(x, y, s=5, alpha=0.6)
plt.xlabel("PCA Component 1")
plt.ylabel("PCA Component 2")
plt.title("Dreams embedded in 2D space (PCA)")
plt.show()